(defvar *final_price* 0)
(defvar *quantity_item* 0)
(defvar *welcome* "---------------------Welcome to the Sab Pizza and pasta Shop---------------------")
(defvar *statement1* "We are Offering Following packages,Please select according to your choice thanks")
(defvar *statement2* "press 0 -> 1 large Pizza = 12 AUD")
(defvar *statement3* "press 1 -> 2 large Pizzas = 22 AUD")
(defvar *statement4* "press 2 -> N large Pizzas = N*10 AUD  (Free 1 garlic Bread for every 3 pizzas) where this package is applied when pizzas are 3 or more than 3 ")
(defvar *statement5* "press 3 -> 1 large Pasta = 8 AUD")
(defvar *statement6* "press 4 -> 2 large pastas = 15 AUD ")
(defvar *statement7* "press 5 -> M Large pastas = M*7 (Free 1.25 Lite soft Drinks for every 3 pastas) where this package is applied when pizzas are 3 or more than 3 pastas ")
(defvar *choice0* "You added 1 large Pizza of 12 AUD in your Cart")
(defvar *deal1* 0)
(defvar *deal1price* 0)
(defvar *choice1* "You added 2 large Pizza of 22 AUD in your Cart")
(defvar *deal2* 0)
(defvar *deal2price* 0)
(defvar *choice2* "How much you want to buy in N deal,N must have greater than 3 or equal to 3 = ")
(defvar *deal3* 0)
(defvar *deal3price* 0)
(defvar *choice3* "You added 1 large pasta of 8 AUD in your Cart ")
(defvar *deal4* 0)
(defvar *deal4price* 0)
(defvar *choice4* "You added 2 large pastas of 15 AUD in your Cart ")
(defvar *deal5* 0)
(defvar *deal5price* 0)
(defvar *choice5* "How much you want to buy in M deal,M must have greater than 3 or equal to 3 =  ")
(defvar *deal6* 0)
(defvar *deal6price* 0)
(defvar *invalid* "Invalid deal")
(defvar *invoice1* "1 large Pizza = 12 AUD  ")
(defvar *invoice2* "2 large Pizzas = 22 AUD ")
(defvar *invoice3* "N large Pizzas = N*10 AUD  (Free 1 garlic Bread for every 3 pizzas) where this package is applied when pizzas are 3 or more than 3")
(defvar *invoice4* "1 large Pasta = 8 AUD")
(defvar *invoice5* "2 large pastas = 15 AUD")
(defvar *invoice6* "M Large pastas = M*7 (Free 1.25 Lite soft Drinks for every 3 pastas) where this package is applied when pizzas are 3 or more than 3 pastas")
(defvar *totl_prc_statment* "Total Price you have to Pay =")
(defvar *seasons* "Do you want to continue session, press 1 for yes or press 0 for no")
(defvar *FinalReport1* "Total Pizza sold in this seasion  =")
(defvar *FinalReport2* "Total Pastas sold in this seasion  =")
(defvar *FinalReport3* "Total price for pizzas sold  =")
(defvar *FinalReport4* "Total price for pastas sold =")
(defvar *totalPizza* 0)
(defvar *totalPasta* 0)
(defvar *tpizzaPrice* 0)
(defvar *tpastaPrice* 0)
(defvar *invoice* "--------------------Invoice Details-------------------- ")
(loop
(loop
	(format t "~a ~%" *welcome* )
	(format t " ~a ~%" *statement1*)
	(format t " ~a ~%" *statement2*)
	(format t " ~a ~%" *statement3*)
	(format t " ~a ~%" *statement4*)
	(format t " ~a ~%" *statement5*)
	(format t " ~a ~%" *statement6*)
	(format t " ~a ~%" *statement7*)
	(format t "press 9 -> to exit  ~%")
	(setq choice (read))
	(case choice
	(0
		(progn
		(format t "~a ~%" *choice0*)
		(setf *deal1price* (+ *deal1price* 12) )
		(setf *deal1* (+ *deal1* 1) )
		))
	(1
		(progn
		(format t "~a ~%" *choice1*)
		(setf *deal2price* (+ *deal2price* 44) )
		(setf *deal2* (+ *deal2* 1) )
		))
	(2
		(progn
		(format t "~a ~%" *choice2*)
		(setq quantity_item (read))
		(if (>= quantity_item 3)
			(progn
		(setf *deal3price* (+ *deal3price*  50 ) )
		(setf *deal3* (+ *deal3* quantity_item) )
		))
		(format t "~a ~%" *invalid* )
		))
	(3
		(progn
		(format t "~a ~%" *choice3*)
		(setf *deal4price* (+ *deal4price* 8) )
		(setf *deal4* (+ *deal4* 1) )
		))
	(4
		(progn
		(format t "~a ~%" *choice4*)
		(setf *deal5price* (+ *deal5price* 30) )
		(setf *deal5* (+ *deal5* 2) )
		))
	(5
		(progn
		(format t "~a ~%" *choice5*)
		(setq quantity_item (read))
		(if (>= quantity_item 3)
			(progn
		(setf *deal6price* (+ *deal6price*  70 ) )
		(setf *deal6* (+ *deal6* quantity_item) )
		))
		(format t "~a ~%" *invalid*)
		))
	)
	(when (= choice 9)(return choice))
	)
(format t "~a ~%" *invoice*)
(when (> *deal1* 0)
(progn
	(format t "~a ~d ~%" *invoice1* *deal1*)
	(setf *final_price* (+ *final_price* *deal1price* ))
	))
(when (> *deal2* 0)
(progn
	(format t "~a ~d ~% "*invoice2* *deal2*)
	(setf *final_price* (+ *final_price* *deal2price* ))
	))
(when (> *deal3* 0)
(progn
	(format t "~a ~d ~%" *invoice3* *deal3*)
	(setf *final_price* (+ *final_price* *deal3price* ))
	))
(when (> *deal4* 0)
(progn
	(format t "~a ~d ~%" *invoice4* *deal4* )
	(setf *final_price* (+ *final_price* *deal4price* ))
	
	))
(when (> *deal5* 0)
(progn
	(format t "~a ~d ~%" *invoice5* *deal5*)
	(setf *final_price* (+ *final_price* *deal5price* ))
	
	))
(when (> *deal6* 0)
(progn
	(format t "~a ~d ~%" *invoice6* *deal6*)
	(setf *final_price* (+ *final_price* *deal6price* ))
	))
(format t "~a ~d ~%" *totl_prc_statment* *final_price*)
(setf *totalPizza* (+ *totalPizza* *deal1* ))
(setf *totalPizza* (+ *totalPizza* *deal2* ))
(setf *totalPizza* (+ *totalPizza* *deal3* ))
(setf *totalPasta* (+ *totalPasta* *deal4* ))
(setf *totalPasta* (+ *totalPasta* *deal5* ))
(setf *totalPasta* (+ *totalPasta* *deal6* ))
(setf *tpizzaPrice* (+ *tpizzaPrice* *deal1price* ))
(setf *tpizzaPrice* (+ *tpizzaPrice* *deal2price* ))
(setf *tpizzaPrice* (+ *tpizzaPrice* *deal3price* ))
(setf *tpastaPrice* (+ *tpastaPrice* *deal4price* ))
(setf *tpastaPrice* (+ *tpastaPrice* *deal5price* ))
(setf *tpastaPrice* (+ *tpastaPrice* *deal6price* ))
(setf *deal1* 0)
(setf *deal2* 0)
(setf *deal3* 0)
(setf *deal4* 0)
(setf *deal5* 0)
(setf *deal6* 0)
(setf *deal1price* 0)
(setf *deal2price* 0)
(setf *deal3price* 0)
(setf *deal4price* 0)
(setf *deal5price* 0)
(setf *deal6price* 0)
(format t "~%")
(format t "~a ~% " *seasons*)
(setq season (read))
(when (= season 0)(return season))
)
(format t "~a ~d ~%" *FinalReport1* *totalPizza*)
(format t "~a ~d ~%" *FinalReport2* *totalPasta*)
(format t "~a ~d ~%" *FinalReport3* *tpizzaPrice*)
(format t "~a ~d ~%" *FinalReport4* *tpastaPrice*)